# Welcome to Online config !

#This define the port that your website that will run.
#****NOTE THAT YOU WILL NEED TO RE-PORTFOREWARD WITH THE NEW PORT****
port: 80

# Here you can choose the pages !
index: index.html
404: 404.html
403: 403.html

# Here you can config pages that user will not be able to see !
denied-pages:
  - /config.yml
  - /router.php

# Here you can choose if the server automaticly disable itself on server stop. 
# DO NOT DISABLE THIS OPTION WHEN YOU'RE USING AN HOSTER ! OR YOU WON4T BE ABLE TO STOP IT !
KillOnShutdown: true