---
name: Online
author:  Ad5001
version: 1.6
api: [2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3,]
description: "You're own website, on PocketMine.'"
main: Ad5001\Online\Main
load: STARTUP
commands: []
permissions: []
...